# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b76d34c4bb33fe84a6cbdf67c9c252710e1aa37049929c7764862ddf51be64e99419ec98110b4171389b862c88832555ef12e9f22f91581348a5fe843dcf5b6

test:
  secret_key_base: d290fa14bed4fe0001b45362eb45c43973676cdcde09b1c3efbc0d54a1f0ef61ccce38559e6317e5cbf1b56296fb7863772ba2ee3ef9b7e271e36e5e82923bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
